### ISSUE TITLE
Carrot Website

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot#1]
To support Carrot 3.0 deployment - move the Carrot "website" to Github pages.

## Tasks

- [ ] Move public carrot.ac.uk site code here
    - [ ] And dependencies
    - [ ] Basically only components necessary to build the website page
- [ ] Make it standalone (remove user check, and make Mapper link configurable by an environment variable)
- [ ] Create a new deployment pipeline for Next.js (Github pages)
- [ ] Update readme to point to:
    - [ ] Carrot Mapper
    - [ ] Carrot Transform
